### ISSUE TITLE
rounded corners

### ISSUE THREAD

**Issue by xuwhite** [Draradech/jigsaw#1]
Could you please make an option for rounded corners? Maybe also with a slider.

**Comment by don-willingham** [comment]
There's a `Corner Radius:` text edit box. It's been there since [e08dc82e](https://github.com/Draradech/jigsaw/commit/e08dc82e), see [here.](https://github.com/Draradech/jigsaw/commit/e08dc82e#diff-d1da1742fa11cb902c163a841a2cfacbb2a2157948280ca08a4af317603b11ddR208)
