### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by don-willingham** [Draradech/jigsaw#2]
Please select an [OSI approved](https://opensource.org/licenses) license for this repository. See https://opensource.guide/starting-a-project/#launching-your-own-open-source-project.

**Comment by don-willingham** [comment]
[Contributing guidelines](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) and [Code of conduct](https://opensource.guide/code-of-conduct/)

**Comment by Draradech** [comment]
Hi there,

for my code parts, you can do whatever you like with it. That would make CC0 (https://creativecommons.org/publicdomain/zero/1.0/) the best fit. If you want to give credit, a link to this repo is fine, but in no way required.

Note, that the save function is pieced together based on a bunch of answers of this stackoverflow: https://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link, that probably makes that part cc-by-sa (unless the posters there didn't have the rights to post it). For that reason I don't have an official license attached to this repo at the whole.

As for contributing guidelines and code of conduct: this is a personal project, made it available to everybody (mainly in the glowforge community: https://community.glowforge.com/t/jigsaw-puzzle-generator/9284). The github infrastructure is useful for version control (and github pages hosting) - I don't forsee this becoming a project with a team, where something like that _may_ be useful.

**Comment by dhouck** [comment]
Thanks for clarifying this!  I have my own puzzle-piece project Iʼm working on, and I was afraid Iʼd need to spend the time learning about Bezier curves and figuring out what a good tab shape would be on my own, but yours are great so I can adapt those.

Thank you!
