### ISSUE TITLE
Circular + Truncate Edge Pieces Overlap Interior Pieces

### ISSUE THREAD

**Issue by MoonRun3s** [Draradech/jigsaw#4]
With both the checkboxes selected, a few notably weird shapes can be seen overlapping eachother in the circle.

**Comment by Draradech** [comment]
Can you attach a screenshot? I have no idea, what you are talking about...

**Comment by MoonRun3s** [comment]
Here is a screenshot of a example:
![image](https://user-images.githubusercontent.com/68448908/106754287-cbc75600-65fa-11eb-9c9b-91f7b46cc723.png)

**Comment by Draradech** [comment]
I see. That has actually nothing to do with circular or truncate edge, and can happen in the rectangular version as well, if you put both tab size and jitter to high values. As big jitter with small tab size and small jitter with big tab size are both valid configurations, I don't have an easy way to fix that. Just don't put both too high at the same time.

- wontfix - closed -
